# action.yml
name: 'Docker Build Tag Publish'
description: 'Build, Tag, and, and Publish a docker image'
branding: 
  icon: tag
  color: red
inputs:
  checkout:
    description: Checkout the repository
    required: false
    default: 'true'
  image_tag:
    description: Tag to override default Logic
    required: false
    default: ''
  use_sha:
    description: Use the SHA for the tag.  Overrides the default logic.
    required: false
    default: 'false'
  

runs:
  using: "composite"
  steps:
    - name: Checkout if required
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@v3
    - name: Tagging Logic
      shell: bash
      run: |
        #Defing variables
        DEFAULT_BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
        IMAGE_TAG=${{ inputs.image_tag }}
        
        REPO_NAME=$(echo $GITHUB_REPOSITORY | sed 's/^.*\///')
        ORG_NAME=$(echo $GITHUB_REPOSITORY | sed 's/\/.*//')
        TAG_OR_HEAD="$(echo $GITHUB_REF | cut -d / -f2)"
        BRANCH_OR_TAG_NAME=$(echo $GITHUB_REF | cut -d / -f3)

        echo "REPO_NAME: $REPO_NAME"
        echo "ORG_NAME: $ORG_NAME"
        echo "TAG_OR_HEAD: $TAG_OR_HEAD"
        echo "BRANCH_OR_TAG_NAME: $BRANCH_OR_TAG_NAME"

        if [ -z "$IMAGE_TAG" ]; then
          if [[ ${{ image.use_sha }} == 'true' ]]; then
            IMAGE_TAG="$GITHUB_SHA"
          else
            if [ "$TAG_OR_HEAD" == "tags" ]; then
              IMAGE_TAG="$BRANCH_OR_TAG_NAME"
            elif [ "$TAG_OR_HEAD" == "heads" ] && [ "$BRANCH_OR_TAG_NAME" == "$DEFAULT_BRANCH" ]; then
              IMAGE_TAG="latest"
            elif [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
              IMAGE_TAG="pr-${GITHUB_HEAD_REF}"
            else
              IMAGE_TAG="$BRANCH_OR_TAG_NAME"
            fi
          fi
        fi
        echo "Image Tag: $IMAGE_TAG"
